//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ctrl_Direccioncliente
    {
        public long Id { get; set; }
        public long IdCliente { get; set; }
        public string Direccion { get; set; }
        public string CodigoPostal { get; set; }
        public string Contacto { get; set; }
    
        public virtual Ctrl_Cliente Ctrl_Cliente { get; set; }
    }
}
