//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ctrl_Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ctrl_Cliente()
        {
            this.Ctrl_Contacto = new HashSet<Ctrl_Contacto>();
            this.Ctrl_Direccioncliente = new HashSet<Ctrl_Direccioncliente>();
            this.Ctrl_TelefonoCliente = new HashSet<Ctrl_TelefonoCliente>();
        }
    
        public long Id { get; set; }
        public string Nombre { get; set; }
        public string Rfc { get; set; }
        public string Pais { get; set; }
        public string Email { get; set; }
        public long IdMercado { get; set; }
    
        public virtual Cat_Mercado Cat_Mercado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ctrl_Contacto> Ctrl_Contacto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ctrl_Direccioncliente> Ctrl_Direccioncliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ctrl_TelefonoCliente> Ctrl_TelefonoCliente { get; set; }
    }
}
