//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MinsaitBDEntities : DbContext
    {
        public MinsaitBDEntities()
            : base("name=MinsaitBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cat_Mercado> Cat_Mercado { get; set; }
        public virtual DbSet<Ctrl_Cliente> Ctrl_Cliente { get; set; }
        public virtual DbSet<Ctrl_Contacto> Ctrl_Contacto { get; set; }
        public virtual DbSet<Ctrl_Direccioncliente> Ctrl_Direccioncliente { get; set; }
        public virtual DbSet<Ctrl_TelefonoCliente> Ctrl_TelefonoCliente { get; set; }
    }
}
